sbarguil/Testing-framework

- git_lab/dh-1.txt
> danielhfile

- fichero_rama_carlos
Comentario sobre pull request de rama de carlos
> Commit fichero rama de carlos

- fichero_rama_carlos
Reverts sbarguil/Testing-framework#4
> Revert "Commit fichero rama de carlos"

- AutomationFramework/capabilities.py
- AutomationFramework/page_objects/base/base_page_object.py
- AutomationFramework/page_objects/interfaces/interfaces.py
- AutomationFramework/test_cases/if_config.yml
- AutomationFramework/test_cases/templates/if_config_loopback_mode.xml
- AutomationFramework/tests/test_if_config.py
- AutomationFramework/utils/rpc_automator_2.py
> [issue_10] Tear down implemented with a fixture

- AutomationFramework/.gitignore
- AutomationFramework/capabilities.py
- AutomationFramework/page_objects/base/base_page_object.py
- AutomationFramework/page_objects/interfaces/interfaces.py
- AutomationFramework/test_cases/if_ethernet.yml
- AutomationFramework/test_cases/templates/if_ethernet_port_speed_state.xml
- AutomationFramework/tests/base_test.py
- AutomationFramework/tests/test_if_ethernet.py
- AutomationFramework/utils/rpc_automator_2.py
- if_ethernet_aggregate_id
- if_ethernet_port_speed
- if_ethernet_duplex_mode
- if_ethernet_auto_negotiate
- get if_ethernet_port_speed_state remaining for implementation
> [pytest] if_ethernet tests 

- AutomationFramework/capabilities.py
- AutomationFramework/page_objects/base/base_page_object.py
- AutomationFramework/page_objects/interfaces/interfaces.py
- AutomationFramework/test_cases/if_ethernet.yml
- AutomationFramework/test_cases/if_subif.yml
- AutomationFramework/test_cases/templates/if_subif_description.xml
- AutomationFramework/test_cases/templates/if_subif_dhcp_client.xml
- AutomationFramework/test_cases/templates/if_subif_enabled.xml
- AutomationFramework/test_cases/templates/if_subif_inner_outer_vlan_id.xml
- AutomationFramework/test_cases/templates/if_subif_ip_prefix_length.xml
- AutomationFramework/test_cases/templates/if_subif_ip_state.xml
- AutomationFramework/test_cases/templates/if_subif_match_vlan_id.xml
- AutomationFramework/test_cases/templates/if_subif_mtu.xml
- AutomationFramework/test_cases/templates/if_subif_origin.xml
- AutomationFramework/test_cases/templates/if_subif_type.xml
- AutomationFramework/test_cases/templates/if_subif_vlan_id.xml
- AutomationFramework/tests/test_if_subif.py
- AutomationFramework/utils/rpc_automator_2.py
- if_subif_type
- if_subif_description
- if_subif_enabled
- if_subif_ip_prefix_length
- if_subif_ip_state
- if_subif_origin
- if_subif_dhcp_client
- if_subif_mtu
- if_subif_vlan_id
- if_subif_inner_outer_vlan_id
- if_subif_match_vlan_id
> [pytest] If_subif tests implementd

- AutomationFramework/capabilities.py
- AutomationFramework/page_objects/base/base_page_object.py
- AutomationFramework/page_objects/interfaces/interfaces.py
- AutomationFramework/test_cases/if_status.yml
- AutomationFramework/test_cases/templates/if_status_admin_status.xml
- AutomationFramework/test_cases/templates/if_status_enabled.xml
- AutomationFramework/test_cases/templates/if_status_name.xml
- AutomationFramework/test_cases/templates/if_status_oper_status.xml
- AutomationFramework/tests/test_if_status.py
- AutomationFramework/utils/rpc_automator_2.py
- test_if_status_admin_status
- test_if_status_enabled
- test_if_status_name
- test_if_status_oper_status
> [pytest] If status tests

- AutomationFramework/page_objects/network_instance/network_intance.py
- AutomationFramework/test_cases/ni_bgp.yml
- AutomationFramework/test_cases/templates/ni_bgp_as.xml
- AutomationFramework/test_cases/templates/ni_bgp_description.xml
- AutomationFramework/test_cases/templates/ni_bgp_enabled.xml
- AutomationFramework/test_cases/templates/ni_bgp_export_policy.xml
- AutomationFramework/test_cases/templates/ni_bgp_import_policy.xml
- AutomationFramework/test_cases/templates/ni_bgp_local_as.xml
- AutomationFramework/test_cases/templates/ni_bgp_multihop_ttl.xml
- AutomationFramework/test_cases/templates/ni_bgp_neighbor_address.xml
- AutomationFramework/test_cases/templates/ni_bgp_peer_as.xml
- AutomationFramework/test_cases/templates/ni_bgp_peer_type.xml
- AutomationFramework/test_cases/templates/ni_bgp_remove_private_as.xml
- AutomationFramework/test_cases/templates/ni_bgp_router_id.xml
- AutomationFramework/tests/network_instance/test_ni_bgp.py
ni | bgp | as
-- | -- | --
ni | bgp | router-id
ni | bgp | description
ni | bgp | local-as
ni | bgp | neighbor-address
ni | bgp | peer-as
ni | bgp | peer-type
ni | bgp | remove-private-as
ni | bgp | enabled
ni | bgp | multihop-ttl
ni | bgp | export-policy
-- | -- | --
ni | bgp | import-policy
> [pytest] Tests implemented, 2 remaining

- AutomationFramework/page_objects/network_instance/network_intance.py
- AutomationFramework/test_cases/ni_protocol_instances.yml
- AutomationFramework/test_cases/templates/ni_protocol_instances_creation.xml
- AutomationFramework/test_cases/templates/ni_protocol_instances_enabled.xml
- AutomationFramework/tests/network_instance/test_ni_protocol_instances.py
ni | protocol_instances | enabled
-- | -- | --
ni | protocol_instances | identifier
ni | protocol_instances | name
> [pytest] NI protocol instances tests

- AutomationFramework/page_objects/network_instance/network_intance.py
- AutomationFramework/test_cases/ni_ospf.yml
- AutomationFramework/test_cases/templates/ni_ospf_authentication_type.xml
- AutomationFramework/test_cases/templates/ni_ospf_id.xml
- AutomationFramework/test_cases/templates/ni_ospf_identifier.xml
- AutomationFramework/test_cases/templates/ni_ospf_interface.xml
- AutomationFramework/test_cases/templates/ni_ospf_network_type.xml
- AutomationFramework/test_cases/templates/ni_ospf_passive.xml
- AutomationFramework/test_cases/templates/ni_ospf_router_id.xml
- AutomationFramework/test_cases/templates/ni_ospf_subinterface.xml
- AutomationFramework/tests/network_instance/test_ni_ospf.py
ni | ospf | identifier
-- | -- | --
ni | ospf | authentication-
ni | ospf | id
ni | ospf | network-type
ni | ospf | passive
ni | ospf | interface
ni | ospf | router-id
ni | ospf | subinterface
-- | -- | --
> [pytest] Ni ospf tests implemented, 1 skipped

- AutomationFramework/page_objects/network_instance/network_intance.py
- AutomationFramework/test_cases/ni_static.yml
- AutomationFramework/test_cases/templates/ni_metric.xml
- AutomationFramework/test_cases/templates/ni_next_hop.xml
- AutomationFramework/test_cases/templates/ni_static_prefix.xml
- AutomationFramework/tests/network_instance/test_ni_static.py
ni | static | prefix
-- | -- | --
ni | static | metric
ni | static | next-hop
> [pytest] ni static tests implemented

- AutomationFramework/page_objects/network_instance/network_intance.py
- AutomationFramework/test_cases/ni_protocol_tables.yml
- AutomationFramework/test_cases/templates/ni_protocol_tables_connection.xml
- AutomationFramework/test_cases/templates/ni_protocol_tables_connection_default_import_policy.xml
- AutomationFramework/test_cases/templates/ni_protocol_tables_connection_import_policy.xml
- AutomationFramework/test_cases/templates/ni_protocol_tables_creation.xml
- AutomationFramework/tests/network_instance/test_ni_protocol_tables.py
ni | protocol_tables | address-family
-- | -- | --
ni | protocol_tables | default-import-policy
ni | protocol_tables | dst-protocol
ni | protocol_tables | src-protocol
ni | protocol_tables | address-family
ni | protocol_tables | protocol
ni | protocol_tables | import-policy
-- | -- | --
> [pytest] Ni protocol tables tests

- AutomationFramework/page_objects/hardware/hardware.py
- AutomationFramework/test_cases/hw_cpu.yml
- AutomationFramework/test_cases/templates/hw_cpu_avg.xml
- AutomationFramework/test_cases/templates/hw_cpu_instant.xml
- AutomationFramework/test_cases/templates/hw_cpu_interval.xml
- AutomationFramework/test_cases/templates/hw_cpu_max.xml
- AutomationFramework/test_cases/templates/hw_cpu_max_time.xml
- AutomationFramework/test_cases/templates/hw_cpu_min.xml
- AutomationFramework/test_cases/templates/hw_cpu_min_time.xml
- AutomationFramework/tests/hardware/test_hw_cpu.py
hw | cpu | oc-cpu:instant
-- | -- | --
hw | cpu | oc-cpu:interval
hw | cpu | oc-cpu:max
hw | cpu | oc-cpu:max-time
hw | cpu | oc-cpu:min
hw | cpu | oc-cpu:min-time
> [pytest] Hw cpu tests

- AutomationFramework/page_objects/hardware/hardware.py
- AutomationFramework/test_cases/hw_component.yml
- AutomationFramework/test_cases/templates/hw_component_description.xml
- AutomationFramework/test_cases/templates/hw_component_hardware_version.xml
- AutomationFramework/test_cases/templates/hw_component_id.xml
- AutomationFramework/test_cases/templates/hw_component_location.xml
- AutomationFramework/test_cases/templates/hw_component_mfg_date.xml
- AutomationFramework/test_cases/templates/hw_component_oper_status.xml
- AutomationFramework/test_cases/templates/hw_component_parent.xml
- AutomationFramework/test_cases/templates/hw_component_serial_no.xml
- AutomationFramework/test_cases/templates/hw_component_type.xml
- AutomationFramework/tests/hardware/test_hw_component.py
hw | component | description
-- | -- | --
hw | component | hardware-version
hw | component | id
hw | component | location
hw | component | mfg-date
hw | component | oper-status
hw | component | parent
hw | component | serial-no
hw | component | type
> [pytest] hw component tests

- AutomationFramework/page_objects/base/base_page_object.py
- AutomationFramework/page_objects/hardware/hardware.py
- AutomationFramework/test_cases/hw_properties.yml
- AutomationFramework/test_cases/templates/hw_properties_name.xml
- AutomationFramework/test_cases/templates/hw_properties_value.xml
- AutomationFramework/tests/hardware/test_hw_properties.py
hw | properties | name | STATE
-- | -- | -- | --
hw | properties | value | STATE
> [pytest] Hw properties tests

- AutomationFramework/page_objects/hardware/hardware.py
- AutomationFramework/test_cases/hw_transceiver.yml
- AutomationFramework/test_cases/templates/hw_transceiver_enabled_state.xml
- AutomationFramework/test_cases/templates/hw_transceiver_slot_id.xml
- AutomationFramework/tests/hardware/test_hw_transceiver.py
hw | transceiver | oc-linecard:slot-id | STATE
-- | -- | -- | --
hw | transceiver | oc-transceiver:enabled | STATE
> [pytest] Hw transceiver tests

- AutomationFramework/page_objects/hardware/hardware.py
- AutomationFramework/test_cases/hw_linecard.yml
- AutomationFramework/test_cases/templates/hw_linecard_power_admin_state.xml
- AutomationFramework/tests/hardware/test_hw_linecard.py
test_hw_linecard_power_admin_state
> [pytest] Hw linecard tests

- AutomationFramework/page_objects/hardware/hardware.py
- AutomationFramework/test_cases/hw_config.yml
- AutomationFramework/tests/hardware/test_hw_config.py
hw | config | name | CONFIG
-- | -- | -- | --
> [pytest] HW config tests

- AutomationFramework/.gitignore
- AutomationFramework/README.md
- AutomationFramework/test_cases/if_config.yml
- AutomationFramework/test_cases/if_ethernet.yml
- AutomationFramework/test_cases/if_status.yml
We can generate excel and html reports
> [pytest] Reports

- AutomationFramework/test_cases/if_subif.yml
- AutomationFramework/test_cases/ni_ospf.yml
- AutomationFramework/tests/hardware/test_hw_config.py
- AutomationFramework/tests/hardware/test_hw_linecard.py
- AutomationFramework/tests/network_instance/test_ni_bgp.py
- AutomationFramework/tests/network_instance/test_ni_config.py
- AutomationFramework/tests/network_instance/test_ni_connection_point.py
- AutomationFramework/tests/network_instance/test_ni_encapsulation.py
- AutomationFramework/tests/network_instance/test_ni_fdb.py
- AutomationFramework/tests/network_instance/test_ni_ospf.py
- AutomationFramework/tests/network_instance/test_ni_protocol_instances.py
- AutomationFramework/tests/network_instance/test_ni_protocol_tables.py
- AutomationFramework/tests/network_instance/test_ni_static.py
- AutomationFramework/tests/qos/test_qos_queue.py
- AutomationFramework/tests/qos/test_qos_scheduler.py
- AutomationFramework/tests/routing_policy/test_rp_community_def.py
- AutomationFramework/tests/routing_policy/test_rp_policy_def.py
- AutomationFramework/tests/test_if_ethernet.py
- AutomationFramework/tests/test_if_subif.py
- AutomationFramework/utils/rpc_automator_2.py
> [pytest] Lists fix

- AutomationFramework/tests/hardware/test_hw_linecard.py
- AutomationFramework/tests/hardware/test_hw_transceiver.py
> [pytest] Tests unskipped
